# Generated by Django 5.1.5 on 2025-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YieldData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=100)),
                ("apy", models.FloatField()),
                ("tvl", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
