# Generated by Django 5.1.5 on 2025-02-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defi", "0002_governanceproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=100)),
                ("tvl", models.FloatField()),
                ("tvl_change_24h", models.FloatField()),
                ("dominance_ratio", models.FloatField()),
                ("volatility_30d", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
