# Generated by Django 5.1.5 on 2025-02-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defi", "0003_riskmetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskmetric",
            name="dominance_ratio",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="riskmetric",
            name="tvl",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="riskmetric",
            name="tvl_change_24h",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="riskmetric",
            name="volatility_30d",
            field=models.FloatField(default=0),
        ),
    ]
