# Generated by Django 5.1.5 on 2025-02-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0007_remove_riskmetric_health_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_volume', models.JSONField(default=list)),
                ('tvl', models.JSONField(default=list)),
                ('wallet_balance', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('audit_status', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniswap_data', models.JSONField(default=list)),
                ('wallet_transactions', models.JSONField(default=list)),
                ('tenderly_simulation', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
