# Generated by Django 5.1.5 on 2025-02-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0008_onchaindata_riskscore_technicaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yielddata',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='yielddata',
            name='tvl',
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyBase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyBase7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyBaseInception',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyMean30d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyPct1D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyPct30D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyPct7D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='apyReward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='chain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='exposure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='il7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='ilRisk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='outlier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='pool',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='poolMeta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='predictions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='rewardTokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='sigma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='stablecoin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='symbol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='tvlUsd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='underlyingTokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='volumeUsd1d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='volumeUsd7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='apy',
            field=models.FloatField(default=0.0),
        ),
    ]
