# Generated by Django 5.1.5 on 2025-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0010_alter_yielddata_apyreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yielddata',
            name='apy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='apyBase',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='chain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='pool',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='predictions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='project',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='rewardTokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='tvlUsd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='underlyingTokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
