# Generated by Django 5.1.5 on 2025-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0011_alter_yielddata_apy_alter_yielddata_apybase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceproposal',
            name='proposal_id',
            field=models.CharField(max_length=100),
        ),
    ]
