# Generated by Django 5.1.5 on 2025-02-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0012_alter_governanceproposal_proposal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskmetric',
            name='category',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='dominance_ratio',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='tvl',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='tvl_change_24h',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='riskmetric',
            name='volatility_30d',
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='audit_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='audits',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='chainTvls',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='chains',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='change_1d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='change_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='cmcId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='forkedFrom',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='gecko_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='hallmarks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='mcap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='misrepresentedTokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='oracles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='tokenBreakdowns',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
