# Generated by Django 5.1.5 on 2025-02-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0013_remove_riskmetric_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governanceproposal',
            name='against_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='governanceproposal',
            name='for_votes',
            field=models.IntegerField(default=0),
        ),
    ]
