# Generated by Django 5.1.5 on 2025-02-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0016_alter_riskscore_audit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskscore',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
